import React from "react";
import HouseAssignments from "./AddGameComponents/HouseAssignments";
import RoundNav from "./AddGameComponents/RoundNav";
import GameInfo from "./AddGameComponents/GameInfo";
import RoundInfo from "./AddGameComponents/RoundInfo";
import { gameFields, houses, gameObject } from "./dataObjects/GameProperties";

export default class AddGame extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      gameId: 0,
      players: [],
      currentRound: 0,
      finalRound: 10,
      gameInfo: {
        name: "",
        month: -1,
        day: -1,
        year: -1
      },
      houseAssignments: {
        lannister: -1,
        greyjoy: -1,
        stark: -1,
        arryn: -1,
        baratheon: -1,
        targaryen: -2,
        dorn: -1,
        tyrell: -1
      },
      round1: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 4,
          boats_start: 3,
          footmen_start: 3,
          knights_start: 2,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 3,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 2,
          strongholds_end: 2,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 3,
          seaTerritories: 1,
          forcedMuster: 0,
          playerNotes: "'Clegane at your back...'"
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 4,
          boats_start: 4,
          footmen_start: 2,
          knights_start: 1,
          siege_start: 0,
          boats_end: 4,
          footmen_end: 2,
          knights_end: 1,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 2,
          seaTerritories: 2,
          forcedMuster: 0,
          playerNotes: "'My fleet is invincible!'"
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 7,
          supply: 4,
          boats_start: 1,
          footmen_start: 4,
          knights_start: 2,
          siege_start: 0,
          boats_end: 1,
          footmen_end: 4,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 2,
          castles_end: 2,
          landTerritories: 5,
          seaTerritories: 1,
          forcedMuster: 0,
          playerNotes: "'I have been forged by winter.'"
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 7,
          supply: 4,
          boats_start: 3,
          footmen_start: 2,
          knights_start: 2,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 2,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 1,
          castles_end: 1,
          landTerritories: 3,
          seaTerritories: 2,
          forcedMuster: 0,
          playerNotes: "'My lands are impenetrable.'"
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 7,
          supply: 4,
          boats_start: 3,
          footmen_start: 2,
          knights_start: 2,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 2,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 1,
          castles_end: 1,
          landTerritories: 3,
          seaTerritories: 2,
          forcedMuster: 0,
          playerNotes: "'I love whores and boars.'"
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 7,
          supply: 4,
          boats_start: 3,
          footmen_start: 2,
          knights_start: 2,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 2,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 1,
          castles_end: 1,
          landTerritories: 3,
          seaTerritories: 2,
          forcedMuster: 0,
          playerNotes: "Targaryen can't be a vassal."
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 7,
          supply: 4,
          boats_start: 3,
          footmen_start: 4,
          knights_start: 1,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 4,
          knights_end: 1,
          siege_end: 0,
          strongholds_start: 1,
          strongholds_end: 1,
          castles_start: 2,
          castles_end: 2,
          landTerritories: 4,
          seaTerritories: 2,
          forcedMuster: 0,
          playerNotes: "'The warm winds are with us.'"
        },
        tyrell: {
          throne: 2,
          sword: 6,
          raven: 1,
          money: 7,
          supply: 2,
          boats_start: 3,
          footmen_start: 2,
          knights_start: 2,
          siege_start: 0,
          boats_end: 3,
          footmen_end: 2,
          knights_end: 2,
          siege_end: 0,
          strongholds_start: 2,
          strongholds_end: 2,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 4,
          seaTerritories: 1,
          forcedMuster: 0,
          playerNotes: "'Roselove sends his regards.'"
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round2: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round3: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round4: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round5: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round6: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round7: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round8: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round9: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      },
      round10: {
        lannister: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        greyjoy: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        stark: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        arryn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        baratheon: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        targaryen: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        dorn: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        tyrell: {
          throne: 7,
          sword: 7,
          raven: 7,
          money: 0,
          supply: 0,
          boats_start: 0,
          footmen_start: 0,
          knights_start: 0,
          siege_start: 0,
          boats_end: 0,
          footmen_end: 0,
          knights_end: 0,
          siege_end: 0,
          strongholds_start: 0,
          strongholds_end: 0,
          castles_start: 0,
          castles_end: 0,
          landTerritories: 0,
          seaTerritories: 0,
          forcedMuster: 0,
          playerNotes: ""
        },
        card1: -1,
        card2: -1,
        card3: -1
      }
    };

    this.playerStartingValues = {
      lannister: {
        throne: 2,
        sword: 6,
        raven: 1,
        money: 7,
        supply: 2,
        boats_start: 1,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      greyjoy: {
        throne: 5,
        sword: 1,
        raven: 6,
        money: 7,
        supply: 2,
        boats_start: 2,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 2,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      stark: {
        throne: 3,
        sword: 4,
        raven: 2,
        money: 7,
        supply: 1,
        boats_start: 1,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 1,
        castles_end: 1,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      arryn: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 1,
        boats_start: 1,
        footmen_start: 0,
        knights_start: 3,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 0,
        knights_end: 3,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 1,
        castles_end: 1,
        landTerritories: 2,
        seaTerritories: 0,
        forcedMuster: 0,
        playerNotes: ""
      },
      baratheon: {
        throne: 1,
        sword: 5,
        raven: 4,
        money: 7,
        supply: 2,
        boats_start: 2,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 2,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      targaryen: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 3,
        footmen_start: 1,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 1,
        knights_end: 2,
        dragons_start: 3,
        dragons_end: 3,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 4,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      dorn: {
        throne: 4,
        sword: 3,
        raven: 3,
        money: 7,
        supply: 2,
        boats_start: 1,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      },
      tyrell: {
        throne: 6,
        sword: 2,
        raven: 5,
        money: 7,
        supply: 2,
        boats_start: 1,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: ""
      }
    };

    this.vassalStartingValues = {
      lannister: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 0,
        supply: 4,
        boats_start: 3,
        footmen_start: 3,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 3,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 2,
        strongholds_end: 2,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 3,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: "'Clegane at your back...'"
      },
      greyjoy: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 0,
        supply: 4,
        boats_start: 4,
        footmen_start: 2,
        knights_start: 1,
        siege_start: 0,
        boats_end: 4,
        footmen_end: 2,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 2,
        seaTerritories: 2,
        forcedMuster: 0,
        playerNotes: "'My fleet is invincible!'"
      },
      stark: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 1,
        footmen_start: 4,
        knights_start: 2,
        siege_start: 0,
        boats_end: 1,
        footmen_end: 4,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 2,
        castles_end: 2,
        landTerritories: 5,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: "'I have been forged by winter.'"
      },
      arryn: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 3,
        footmen_start: 2,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 2,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 1,
        castles_end: 1,
        landTerritories: 3,
        seaTerritories: 2,
        forcedMuster: 0,
        playerNotes: "'My lands are impenetrable.'"
      },
      baratheon: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 3,
        footmen_start: 2,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 2,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 1,
        castles_end: 1,
        landTerritories: 3,
        seaTerritories: 2,
        forcedMuster: 0,
        playerNotes: "'I love whores and boars.'"
      },
      targaryen: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 3,
        footmen_start: 2,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 2,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 1,
        castles_end: 1,
        landTerritories: 3,
        seaTerritories: 2,
        forcedMuster: 0,
        playerNotes: "Targaryen can't be a vassal."
      },
      dorn: {
        throne: 7,
        sword: 7,
        raven: 7,
        money: 7,
        supply: 4,
        boats_start: 3,
        footmen_start: 4,
        knights_start: 1,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 4,
        knights_end: 1,
        siege_end: 0,
        strongholds_start: 1,
        strongholds_end: 1,
        castles_start: 2,
        castles_end: 2,
        landTerritories: 4,
        seaTerritories: 2,
        forcedMuster: 0,
        playerNotes: "'The warm winds are with us.'"
      },
      tyrell: {
        throne: 2,
        sword: 6,
        raven: 1,
        money: 7,
        supply: 2,
        boats_start: 3,
        footmen_start: 2,
        knights_start: 2,
        siege_start: 0,
        boats_end: 3,
        footmen_end: 2,
        knights_end: 2,
        siege_end: 0,
        strongholds_start: 2,
        strongholds_end: 2,
        castles_start: 0,
        castles_end: 0,
        landTerritories: 4,
        seaTerritories: 1,
        forcedMuster: 0,
        playerNotes: "'Roselove sends his regards.'"
      }
    };

    this.onClick_IncrementRound = this.onClick_IncrementRound.bind(this);
    this.onClick_DecrementRound = this.onClick_DecrementRound.bind(this);
    this.fetchPlayers = this.fetchPlayers.bind(this);
    this.fetchGameCount = this.fetchGameCount.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.loadFromPrevious = this.loadFromPrevious.bind(this);
    this.updateRound1Data = this.updateRound1Data.bind(this);
    this.checkRound1 = this.checkRound1.bind(this);
  }

  fetchPlayers() {
    fetch("/getPlayers")
      .then(response => {
        console.log("App fetching: " + JSON.stringify(response));
        return response.json();
      })
      .then(data => this.setState({ players: data }));
  }

  fetchGameCount() {
    fetch("/getGamesCount")
      .then(response => {
        console.log("App fetching: " + JSON.stringify(response));
        return response.json();
      })
      .then(data => this.setState({ gameId: data[0].count }));
  }

  onClick_IncrementRound() {
    if (this.state.currentRound < 10) {
      this.setState(state => {
        // Important: read `state` instead of `this.state` when updating.
        return { currentRound: state.currentRound + 1 };
      });
    } else if (this.state.currentRound === 10) {
      this.setState(state => {
        // Important: read `state` instead of `this.state` when updating.
        return { currentRound: 0 };
      });
    }

    let elts = document.getElementsByClassName("fieldSelect");

    for (let i = 0; i < elts.length; i++) {
      elts[i].setAttribute(
        "style",
        "background-color: lightlightgray; width:4em; float:right; display:inline; margin:0px; padding:0px;border:0px;"
      );
    }
  }

  onClick_DecrementRound() {
    if (this.state.currentRound > 0) {
      this.setState(state => {
        // Important: read `state` instead of `this.state` when updating.
        return { currentRound: state.currentRound - 1 };
      });
    } else if (this.state.currentRound === 0) {
      this.setState(state => {
        // Important: read `state` instead of `this.state` when updating.
        return { currentRound: 10 };
      });
    }

    // Get the elements by class name
    let elts = document.getElementsByClassName("fieldSelect");

    for (let i = 0; i < elts.length; i++) {
      elts[i].setAttribute(
        "style",
        "background-color: lightlightgray; width:4em; float:right; display:inline; margin:0px; padding:0px;border:0px;"
      );
    }
  }

  handleChange() {
    console.log("an element was changed! saving data!");
    if (this.state.currentRound === 0) {
      this.setState({
        finalRound: document.getElementById("gameInfo_finalRound").value,
        gameInfo: {
          name: document.getElementById("gameInfo_name").value,
          month: document.getElementById("gameInfo_month").value,
          day: document.getElementById("gameInfo_day").value,
          year: document.getElementById("gameInfo_year").value
        },
        houseAssignments: {
          lannister: document.getElementById("houseAssignment_lannisterPlayer")
            .value,
          greyjoy: document.getElementById("houseAssignment_greyjoyPlayer")
            .value,
          stark: document.getElementById("houseAssignment_starkPlayer").value,
          arryn: document.getElementById("houseAssignment_arrynPlayer").value,
          baratheon: document.getElementById("houseAssignment_baratheonPlayer")
            .value,
          targaryen: document.getElementById("houseAssignment_targaryenPlayer")
            .value,
          dorn: document.getElementById("houseAssignment_dornPlayer").value,
          tyrell: document.getElementById("houseAssignment_tyrellPlayer").value
        }
      });
    } else {
      this.setState(state => {
        const prevState = { ...state };

        houses.forEach(house => {
          gameFields.forEach(field => {
            let roundNum = "round" + this.state.currentRound;
            let elementId =
              "round" + this.state.currentRound + "_" + field + "_" + house;

            console.log("elementID = " + elementId);

            prevState[roundNum][house][field] = document.getElementById(
              elementId
            ).value;
          });
        });

        // Important: read `state` instead of `this.state` when updating.
        return {
          ...prevState
        };
      });
    }

    // console.log(JSON.stringify(this.state.houseAssignments));
    // console.log(
    //   "round " +
    //     this.state.currentRound +
    //     " = " +
    //     JSON.stringify(this.state["round" + this.state.currentRound])
    // );
  }

  loadFromPrevious() {
    this.setState(prevState => {
      let stateCopy = { ...prevState };

      houses.forEach(house => {
        let roundNum = "round" + this.state.currentRound;
        let prevRoundNum = "round" + (this.state.currentRound - 1);

        stateCopy[roundNum][house] = {
          ...prevState[prevRoundNum][house]
        };

        stateCopy[roundNum][house].boats_start =
          prevState[prevRoundNum][house].boats_end;
        stateCopy[roundNum][house].footmen_start =
          prevState[prevRoundNum][house].footmen_end;
        stateCopy[roundNum][house].knights_start =
          prevState[prevRoundNum][house].knights_end;
        stateCopy[roundNum][house].siege_start =
          prevState[prevRoundNum][house].siege_end;
        stateCopy[roundNum][house].playerNotes = "";
      });

      return {
        ...stateCopy
      };
    });
  }

  changeEnding() {
    // {"round" + this.props.round + "_castles_start_" + house}
  }

  updateRound1Data(event) {
    console.log("a vassal has been detected");

    houses.forEach(house => {
      let elId = "houseAssignment_" + house.toLowerCase() + "Player";
      if (event.target.id === elId) {
        console.log("id matches: " + elId);
        if (event.target.value == -1) {
          console.log("Updating " + house + " units to vassal start");

          this.setState(prevState => {
            const newState = { ...prevState };
            newState.round1[house] = this.vassalStartingValues[house];

            return {
              newState
            };
          });
        } else if (event.target.value == -2) {
        } else {
          console.log("Updating " + house + " units to vassal start");

          this.setState(prevState => {
            const newState = { ...prevState };
            newState.round1[house] = this.playerStartingValues[house];

            return {
              newState
            };
          });
        }
      }
    });
  }

  checkRound1() {
    console.log(JSON.stringify(this.state.round1));
  }

  checkGameObjectProperties() {
    console.log(JSON.stringify(gameObject));
  }

  componentDidMount() {
    this.fetchPlayers();
    this.fetchGameCount();
    console.log("gameobject.hi is " + gameObject.round1_lannister_castles);
  }

  componentWillUnmount() {}

  returnDisplay() {
    if (this.state.currentRound === 0) {
      return (
        <>
          <GameInfo gameId={this.state.gameId} saved={this.state.gameInfo} />
          <br />
          <button onClick={this.checkRound1}>Check Round 1</button>
          <button onClick={this.checkGameObjectProperties}>
            Check GameObject
          </button>
          <HouseAssignments
            players={this.state.players}
            saved={this.state.houseAssignments}
            finalRound={this.state.finalRound}
            visitedRound1={this.state.visitedRound1}
            updateRound1Data={this.updateRound1Data}
          />
        </>
      );
    } else if (this.state.currentRound > 0) {
      return (
        <>
          <RoundInfo
            round={this.state.currentRound}
            saved={this.state["round" + this.state.currentRound]}
            loadFromPrevious={this.loadFromPrevious}
            houseAssignments={this.state.houseAssignments}
            players={this.state.players}
          />
        </>
      );
    } else {
      return <div>Invalid Round Number</div>;
    }
  }

  render() {
    return (
      <div>
        <h2>ADD GAME</h2>
        <RoundNav
          roundNumber={this.state.currentRound}
          incrementRound={this.onClick_IncrementRound}
          decrementRound={this.onClick_DecrementRound}
        />
        <br />
        <br />
        <div onChange={this.handleChange}>{this.returnDisplay()}</div>
      </div>
    );
  }
}
